# 4.6 GPU计算

In [ ]:
## 4.6 GPU 计算
# 02-25 15；14 on 超算

In [2]:
!nvidia-smi

Fri Feb  5 07:12:47 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 418.67       Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:8A:00.0 Off |                    0 |
| N/A   37C    P0    55W / 300W |   2547MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:8B:00.0 Off |                    0 |
| N/A   34C    P0    51W / 300W |   1885MiB / 16130MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   2  T

## 1.计算设备

In [3]:
import torch
from torch import nn
# 是否可用
torch.cuda.is_available()

True

查看GPU数量：

In [4]:
torch.cuda.device_count()

4

查看当前GPU索引号，索引号从0开始：

In [5]:
torch.cuda.current_device()

0

根据索引号查看GPU名字:

In [6]:
torch.cuda.get_device_name(0)

'Tesla V100-SXM2-16GB'

## 2.Tensor的GPU计算

默认情况下，Tensor会被存在内存上。因此，之前我们每次打印Tensor的时候看不到GPU相关标识。

In [10]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

使用.cuda()可以将CPU上的Tensor转换（复制）到GPU上。如果有多块GPU，我们用.cuda(i)来表示第 ii 块GPU及相应的显存（ii从0开始）且cuda(0)和cuda()等价。

In [12]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

我们可以通过Tensor的device属性来查看该Tensor所在的设备。

In [13]:
x.device

device(type='cuda', index=0)

我们可以直接在创建的时候就指定设备。

In [15]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)

# or x = torch.tensor([1,2,3]).to(device)

x

tensor([1, 2, 3], device='cuda:0')

如果对在GPU上的数据进行运算，那么结果还是存放在GPU上。



In [17]:
y = x ** 2
y

tensor([1, 4, 9], device='cuda:0')

需要注意的是，存储在不同位置中的数据是不可以直接进行计算的。即存放在CPU上的数据不可以直接与存放在GPU上的数据进行运算，位于不同GPU上的数据也是不能直接进行计算的。

In [18]:
z = y + x.cpu()

RuntimeError: expected device cuda:0 but got device cpu

## 3.模型的GPU计算

同Tensor类似，PyTorch模型也可以通过.cuda转换到GPU上。我们可以通过检查模型的参数的device属性来查看存放模型的设备。

In [20]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

可见模型在CPU上，将其转换到GPU上：

In [21]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)